blog/config/routes.rb
Blog::Application.routes.draw do

  #musimy uzyc to - bo ZMIENIAMY routsy - railsy musza wiedziec do jakiego Kontrollera trafi
  #musimy wskazac do jakiego kontolera ma trafic
  get "winter-promo", to: 'winter_promo#show', as: 'winter_promo'

  post "winter-promo/save", to: 'winter_promo#save', as: 'winter_promo_save'

  get "winter-promo/success", to: 'winter_promo#success', as: 'winter_promo_success'

  get "contacts/new"

  post "contacts/send_form"

  devise_for :users

  #komentzrze sa zalezne od postow
  #i jest tylko akcja create komentarzy - chcemy tylko tworzy ckomentarze do postw

  # w resources posts mamy komentarze
  resources :posts do
    resources :comments, :only => [:create]
    post 'alert', :to =>'posts#alert_post', :on => :member
  end

  get '/set-terms-cookie', to: 'statics#set_cookie', as: 'set_cookie_terms'

  match '/landing/summer', to: 'landing_pages#summer_promo', as: 'landing_pages_summer_promo', via: [:get, :post]
  get '/landing/success', to: 'landing_pages#promo_success', as: 'landing_pages_promo_success'


  root :to => "statics#home"
end




#
# 1.szy parametr - jak adres wyglada w url przegladarki
# 2gi parametr wskazuje na jaki kontroller i akcje ma uderzac
# konroller - statics  , akcja -set_cookie
# 3. indentyfikator z routes
#
# rake routes - pierwsza kolumna to identyfikator

blog/app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :body, :title, :updated_at, :visits_count, :avatar, :remove_avatar, :avatar_file_name
  attr_accessor :remove_avatar

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  validates_presence_of :body, :title
  #chcemy zeby body mialo minimum 5 znakow:
  validates_length_of :body, :minimum => 5
  validates :title, :length => {:minimum => 3}
  validate :must_be_first_letter, :on => :create

  #to nam odwzorowuje tabele komentarzy
  #jak by byl 1 - has_one :comment
  has_many :comments
  has_many :alerts
  belongs_to :user

  scope :latest_published, order("created_at DESC").limit(5)

  before_save :delete_avatar, if: ->{ remove_avatar == '1' && !avatar_updated_at_changed? }
  before_validation :zamiana_litery

  def full_title
    "#{title} [#{updated_at.strftime('%m/%d/%Y')}]"
  end

  def self.ordered(type)
    order("updated_at #{type}")
  end

  def must_be_first_letter
    if self.title.present?
      errors.add(:title, "must have first LETTER") unless self.title.match(/^[a-zA-Z]/)
    end
  end

  private

    def delete_avatar
      self.avatar = nil
    end

    def zamiana_litery
      self.title[0] = self.title[0].upcase
    end
end

blog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show]
  after_filter :notify_log, :only => [:create]

  def alert_post
    #uzytjkownik klika i sie ta metoda wywoluje:
    #date_zgloszenia, id_postu, ilosc_zgloszen
    # polaczyc relacje z innym modelem musze:
    #1. musze ZNALESC POSTA:
    @post = Post.find(params[:id])
    #polaczyc POSTA z ALERTEM - laczymy zawsze po id
    @alert = @post.alerts.build
    @alert.alert_count = @alert.alert_count + 1
    @alert.alert_date = Time.now
    @alert.save

    render json: @alert
    # powyzej juz mamy akcje
  end

  def index
    #@posts = Post.all

    @posts = Post.paginate(:page => params[:page], :per_page => 7)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
    @post.visits_count = @post.visits_count + 1
    @post.save
    #@post.update_attribute(:visits_count, @post.visits_count + 1)


    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = current_user.posts.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = current_user.posts.where(id: params[:id]).first
    if @post.nil?
      redirect_to posts_path, notice: 'post not found'
    end
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(params[:post])
    @post.save

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = current_user.posts.where(id: params[:id]).first

    if @post.nil?
      redirect_to posts_url, notice: 'post not found'
    else
      if @post.update_attributes(params[:post])
       redirect_to @post, notice: 'Post was successfully updated.'
      else
        render action: "edit"
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = current_user.posts.where(id: params[:id]).first
    if @post.nil?
      redirect_to posts_url, notice: 'post not found'
    else
      @post.destroy
      redirect_to posts_url
    end
  end

  private

    def notify_log
      #puts '____________________________________________________'
    end

end

blog/app/views/posts/_form.html.erb
<div class="row">
  <div class="col-md-6">

  <%= form_for @post, html: { multipart: true } do |f|  %>
    <% if @post.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

        <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <p>wklej sobie obrazek:</p>
    <div class="form-group">
      <% if @post.avatar? %>

        <%= link_to @post.avatar.url, :target => '_blank' do %>
          <%= image_tag @post.avatar.url(:thumb) %>
        <% end %>
        <br>
        <%= f.label :remove_avatar do %>

          <%= f.check_box :remove_avatar %>
          remove avatar bla vla
        <% end %>
      <% end %>
      <br>
      <%= f.file_field :avatar %>
    </div>

    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control', placeholder: 'Tytul'  %>
    </div>
    <div class="form-group">
      <%= f.label :body %>
      <%= f.text_area :body, rows: 3, class: 'form-control', placeholder: 'Tresc' %>
    </div>
      <%= f.submit "Save", class: 'btn btn-default' %>
  <% end %>
  </div>
</div>

blog/app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

blog/app/views/posts/index.html.erb
<div class="row">
  <div class="col-md-10">
    <h2 style="margin-top: 0">Listing posts</h2>
  </div>
  <div class="col-md-2">
    <div class="pull-right">
      <%= link_to 'New Post', new_post_path, class: 'btn btn-info', role: 'button' %>
    </div>
  </div>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Author</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  <% @posts.each do |post| %>
    <tr>
      <%# chcemy miec full title: %>
      <td><%= post.full_title %></td>
      <td><%= post.body %></td>
      <td><%= post.user.email %></td>
      <td><%= link_to 'Show', post %></td>
      <% if current_user.present? and current_user.id == post.user_id %>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% else %>
        <td></td>
        <td></td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>

<div class="row">
  <div class="col-xs-6 col-md-4"></div>
  <div class="col-xs-6 col-md-4">
    <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
  </div>
  <div class="col-xs-6 col-md-4"></div>
</div>

blog/app/views/posts/new.html.erb
<h2>New post</h2>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

blog/app/views/posts/show.html.erb
<div class="row">
  <div class="col-xs-8">
    <% if user_signed_in? && current_user.id == @post.user_id %>
      <%= link_to 'Edit', edit_post_path(@post), class: 'btn btn-success' %>
    <% end %>
  </div>
  <div class="col-xs-4">
    <div class="pull-right">
      <% if user_signed_in? && current_user.id != @post.user_id %>
        <%= link_to 'Zglos problem', alert_post_path, :remote => true, :method => :post, :id => 'notify_problem', class: "btn btn-info" %>
      <% end %>
      <%= link_to 'Back', posts_path, class: 'btn btn-warning' %>
    </div>
  </div>
</div>

<p id="notice"><%= notice %></p>
<div id='notify_message'></div>

<table class="table">
  <thead>
    <tr>
      <th>Author:</th>
      <th>Title:</th>
      <th>Body:</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @post.user.email %></td>
      <td><%= @post.title %></td>
      <td><%= @post.body %></td>
    </tr>
  </tbody>
</table>

<% if @post.avatar? %>
  <%= link_to @post.avatar.url, :target => '_blank' do %>
    <%= image_tag @post.avatar.url(:thumb) %>
  <% end %>
<% end %>

<hr>
<h5 class="text-right"> ilosc wyswietlen <%= @post.visits_count %></h5>
<div class="row">
  <div class="col-md-8">
    <h3>Comments</h3>
    <div id="comments">
      <%= render :partial => @post.comments %>
    </div>
    <%= form_for [@post, Comment.new] do |f| %>
      <div class="form-group">
        <%= f.label :author, "Author" %>
        <%= f.text_field :author, class: "form-control", placeholder: "Author" %>
      </div>
      <div class="form-group">
        <%= f.label :body, "New comment" %>
        <%= f.text_area :body, class: "form-control", placeholder: "Your Comment", rows: 3 %>
      </div>
      <%= f.submit "Add Comment", class: "btn btn-info" %>
    <% end %>
  </div>
  <div class="col-md-4"></div>
</div>