blog/config/routes.rb
Blog::Application.routes.draw do

  #musimy uzyc to - bo ZMIENIAMY routsy - railsy musza wiedziec do jakiego Kontrollera trafi
  #musimy wskazac do jakiego kontolera ma trafic
  get "winter-promo", to: 'winter_promo#show', as: 'winter_promo'

  post "winter-promo/save", to: 'winter_promo#save', as: 'winter_promo_save'

  get "winter-promo/success", to: 'winter_promo#success', as: 'winter_promo_success'

  get "contacts/new"

  post "contacts/send_form"

  devise_for :users

  #komentzrze sa zalezne od postow
  #i jest tylko akcja create komentarzy - chcemy tylko tworzy ckomentarze do postw

  # w resources posts mamy komentarze
  resources :posts do
    resources :comments, :only => [:create]
    post 'alert', :to =>'posts#alert_post', :on => :member
  end

  get '/set-terms-cookie', to: 'statics#set_cookie', as: 'set_cookie_terms'

  match '/landing/summer', to: 'landing_pages#summer_promo', as: 'landing_pages_summer_promo', via: [:get, :post]
  get '/landing/success', to: 'landing_pages#promo_success', as: 'landing_pages_promo_success'


  root :to => "statics#home"
end




#
# 1.szy parametr - jak adres wyglada w url przegladarki
# 2gi parametr wskazuje na jaki kontroller i akcje ma uderzac
# konroller - statics  , akcja -set_cookie
# 3. indentyfikator z routes
#
# rake routes - pierwsza kolumna to identyfikator

blog/app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :body, :email, :subject

  validates_presence_of :body, :email, :subject
end

blog/app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    #w widoku mielismy - new.html.erb mielismy zmienna @contact - wiec ja tworzymy
    @contact = Contact.new
  end

  def send_form
    @contact = Contact.new(params[:contact])
    if @contact.save
      redirect_to contacts_new_path, notice: 'udalo sie zapisac wiadomosc!'
    else
      render :new
    end
  end
end

blog/app/views/contacts/new.html.erb
<h2>Nowy kontakt</h2>

<div class="row">
  <div class="col-xs-6">

    <%= form_for(@contact, :url => contacts_send_form_path) do |f| %>
      <% if @contact.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this post from being saved:</h2>

          <ul>
            <% @contact.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.label :email %><br />
        <%= f.text_field :email, class: 'form-control', placeholder: 'your email' %>
      </div>
      <div class="form-group">
        <%= f.label :subject %><br />
        <%= f.text_field :subject, class: 'form-control', placeholder: 'subject of the post' %>
      </div>
      <div class="form-group">
        <%= f.label :body %><br />
        <%= f.text_area :body, class: 'form-control', placeholder: 'leave your comment here', rows: 3 %>
      </div>
      <div class="actions">
        <button class="btn btn-info" type="submit">Create Contact</button>
        </div>
      </div>
  </div>

<% end %>