blog/config/routes.rb
Blog::Application.routes.draw do

  #musimy uzyc to - bo ZMIENIAMY routsy - railsy musza wiedziec do jakiego Kontrollera trafi
  #musimy wskazac do jakiego kontolera ma trafic
  get "winter-promo", to: 'winter_promo#show', as: 'winter_promo'

  post "winter-promo/save", to: 'winter_promo#save', as: 'winter_promo_save'

  get "winter-promo/success", to: 'winter_promo#success', as: 'winter_promo_success'

  get "contacts/new"

  post "contacts/send_form"

  devise_for :users

  #komentzrze sa zalezne od postow
  #i jest tylko akcja create komentarzy - chcemy tylko tworzy ckomentarze do postw

  # w resources posts mamy komentarze
  resources :posts do
    resources :comments, :only => [:create]
    post 'alert', :to =>'posts#alert_post', :on => :member
  end

  get '/set-terms-cookie', to: 'statics#set_cookie', as: 'set_cookie_terms'

  match '/landing/summer', to: 'landing_pages#summer_promo', as: 'landing_pages_summer_promo', via: [:get, :post]
  get '/landing/success', to: 'landing_pages#promo_success', as: 'landing_pages_promo_success'


  root :to => "statics#home"
end




#
# 1.szy parametr - jak adres wyglada w url przegladarki
# 2gi parametr wskazuje na jaki kontroller i akcje ma uderzac
# konroller - statics  , akcja -set_cookie
# 3. indentyfikator z routes
#
# rake routes - pierwsza kolumna to identyfikator

blog/app/views/layouts/_menu.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'main page', root_path %></li>
        <li><%= link_to 'blog', posts_path %></li>
        <li><%= link_to 'contact', contacts_new_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= current_user.discount_percent %></li>
          <li><%= link_to 'edytuj profil', edit_user_registration_path %></li>
          <li><%= link_to 'wyloguj', destroy_user_session_path %></li>
      <% else %>
          <li><%= link_to 'zaloguj sie', new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

blog/app/views/layouts/_notifications.html.erb
<% flash.each do |level, message| %>
  <div class="alert <%= flash_css_class(level.to_sym) %>">
    <strong><%= message %></strong>
  </div>
<% end %>

blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= stylesheet_link_tag    "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css", :media => "all" %>

  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/menu' %>

<div class="container">
  <%= render 'layouts/notifications' %>


  <%= yield %>

  <br><br><h5>jestes na tej stronie <%= session[:views].to_i %> raz </h5><br><br>
</div>


<!--unless - pokazujemy te wiadomosc i czekamy n ainterackjce uzytkownika, jak mamy cookies - nie pokazujamy-->
<% unless cookies['cookie_terms'] %>
  <div data-selector="cookies-info">
    Używamy plików cookies i podobnych technologii w celu realizacji usług oraz statystycznych. Korzystanie z witryny bez zmiany ustawień przeglądarki internetowej oznacza zgodę na zapisanie i dostęp do tych plików. Więcej szczegółów, w Polityce prywatności.
    <button data-selector="cookies-info-close" type="button">Zamknij [js]</button>
    <%= link_to 'Zamkin [ruby]', set_cookie_terms_path %>
  </div>
<% end %>
<%= javascript_include_tag "application" %>

</body>
</html>